In [30]:
pip install pandas pyarrow fsspec s3fs

Requirement already satisfied: pandas in /usr/local/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.11/site-packages (19.0.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/site-packages (2025.3.2)
Requirement already satisfied: s3fs in /usr/local/lib/python3.11/site-packages (2025.3.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: aiobotocore<3.0.0,>=2.5.4 in /usr/local/lib/python3.11/site-packages (from s3fs) (2.21.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/site-packages (from s3fs) (3.11.18)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (0.12.0)
Requirement already satisfied: botocore<1.37.2,>=1.37.0 in /usr/local/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.37.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.0.1)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /usr/local/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (6.4.3)
Requirement already satisfied: wrapt<2.0.0,>=1.10.10 in /usr/local/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.6.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.11/site-packages (from botocore<1.37.2,>=1.37.0->aiobotocore<3.0.0,>=2.5.4->s3fs) (2.2.2)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (3.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests
import pandas as pd
from datetime import datetime
import pytz

# API endpoint and parameters
WEATHER_ENDPOINT = "https://api.openweathermap.org/data/2.5/weather"
API_KEY = "70e208d9d8ba1534136297fb1f3fe396"  # Replace with your actual API key


provinces = {
    "Pathum Thani":{
        "lat": 14.0134,
        "lon": 100.5304
    },
    "Bangkok":{
            "lat": 13.7367,
            "lon": 100.5232
    },
    "Chiang Mai":{
        "lat": 18.7883,
        "lon": 98.9853
    },
    "Phuket":{
        "lat": 7.9519,
        "lon": 98.3381
    }
}
# Function to fetch and process weather data
def get_weather_data(province='Pathum Thani'):
    
    params = {
        "lat": provinces[province]['lat'],
        "lon": provinces[province]['lon'],
        "appid": API_KEY,
        "units": "metric"
    }
    try:
        # Make API request
        response = requests.get(WEATHER_ENDPOINT, params=params)
        response.raise_for_status()  # Raise an exception for bad status codes
        data = response.json()
        
        # Convert timestamp to datetime
        # created_at = datetime.fromtimestamp(data['dt'])

        dt = datetime.now()
        thai_tz = pytz.timezone('Asia/Bangkok')
        created_at = dt.replace(tzinfo=thai_tz)


        timestamp = datetime.now()
        
        # Create dictionary with required fields
        weather_dict = {
            'timestamp': timestamp,
            'year': timestamp.year,
            'month': timestamp.month,
            'day': timestamp.day,
            'hour': timestamp.hour,
            'minute': timestamp.minute,
            'created_at': created_at,
            'requested_province':province,
            'location': data['name'],
            'weather_main': data['weather'][0]['main'],
            'weather_description': data['weather'][0]['description'],
            'main.temp': data['main']['temp']
        }
        
        # Create DataFrame
        # df = pd.DataFrame([weather_dict])
        
        # return df
        return weather_dict
    
    except requests.exceptions.RequestException as e:
        print(f"Error fetching data: {e}")
        return None
    except KeyError as e:
        print(f"Error processing data: Missing key {e}")
        return None

In [3]:
df=pd.DataFrame([get_weather_data(p) for p in list(provinces.keys())])
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            4 non-null      datetime64[ns]
 1   year                 4 non-null      int64
 2   month                4 non-null      int64
 3   day                  4 non-null      int64
 4   hour                 4 non-null      int64
 5   minute               4 non-null      int64
 6   created_at           4 non-null      datetime64[ns, Asia/Bangkok]
 7   requested_province   4 non-null      object
 8   location             4 non-null      object
 9   weather_main         4 non-null      object
 10  weather_description  4 non-null      object
 11  main.temp            4 non-null      float64
dtypes: datetime64[ns, Asia/Bangkok](1), datetime64[ns](1), float64(1), int64(5), object(4)
memory usage: 516.0+ bytes

,timestamp,year,month,day,hour,minute,created_at,requested_province,location,weather_main,weather_description,main.temp
0,2025-05-01 11:31:10.350466,2025,5,1,11,31,2025-05-01 11:49:10.333970+07:00,Pathum Thani,Pathum Thani,Clouds,few clouds,33.15
1,2025-05-01 11:31:10.717529,2025,5,1,11,31,2025-05-01 11:49:10.717493+07:00,Bangkok,Bangkok,Clouds,overcast clouds,33.94
2,2025-05-01 11:31:11.057869,2025,5,1,11,31,2025-05-01 11:49:11.057842+07:00,Chiang Mai,Chiang Mai,Clouds,few clouds,31.28
3,2025-05-01 11:31:11.341738,2025,5,1,11,31,2025-05-01 11:49:11.341696+07:00,Phuket,Kathu,Rain,moderate rain,25.92

In [7]:

dt = datetime.now()
thai_tz = pytz.timezone('Asia/Bangkok')
dt = dt.replace(tzinfo=thai_tz)
print(dt)

2025-05-01 11:31:40.647329+06:42

In [11]:
import pandas as pd

# lakeFS credentials from your docker-compose.yml
ACCESS_KEY = "access_key"
SECRET_KEY = "secret_key"

# lakeFS endpoint (running locally)
lakefs_endpoint = "http://lakefs-dev:8000/"

# lakeFS repository, branch, and file path
repo = "weather"
branch = "main"
path = "weather.parquet"

# Construct the full lakeFS S3-compatible path
lakefs_s3_path = f"s3a://{repo}/{branch}/{path}"

# Configure storage_options for lakeFS (S3-compatible)
storage_options = {
    "key": ACCESS_KEY,
    "secret": SECRET_KEY,
    "client_kwargs": {
        "endpoint_url": lakefs_endpoint
    }
}

In [12]:
df.to_parquet(
    lakefs_s3_path,
    storage_options=storage_options,
    partition_cols=['year','month','day','hour'],
    
)

# test read parquet files

In [14]:
path_all_partition = 's3a://weather/main/weather.parquet'

df2=pd.read_parquet(    
    path=path_all_partition,
    storage_options=storage_options
)
df2.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            8 non-null      datetime64[ns]
 1   minute               8 non-null      int64
 2   created_at           8 non-null      datetime64[ns, Asia/Bangkok]
 3   requested_province   8 non-null      object
 4   location             8 non-null      object
 5   weather_main         8 non-null      object
 6   weather_description  8 non-null      object
 7   main.temp            8 non-null      float64
 8   year                 8 non-null      category
 9   month                8 non-null      category
 10  day                  8 non-null      category
 11  hour                 8 non-null      category
dtypes: category(4), datetime64[ns, Asia/Bangkok](1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 1.0+ KB

,timestamp,minute,created_at,requested_province,location,weather_main,weather_description,main.temp,year,month,day,hour
0,2025-05-01 11:31:10.350466,31,2025-05-01 11:49:10.333970+07:00,Pathum Thani,Pathum Thani,Clouds,few clouds,33.15,2025,5,1,11
1,2025-05-01 11:31:10.717529,31,2025-05-01 11:49:10.717493+07:00,Bangkok,Bangkok,Clouds,overcast clouds,33.94,2025,5,1,11
2,2025-05-01 11:31:11.057869,31,2025-05-01 11:49:11.057842+07:00,Chiang Mai,Chiang Mai,Clouds,few clouds,31.28,2025,5,1,11
3,2025-05-01 11:31:11.341738,31,2025-05-01 11:49:11.341696+07:00,Phuket,Kathu,Rain,moderate rain,25.92,2025,5,1,11
4,2025-05-01 11:31:10.350466,31,2025-05-01 11:49:10.333970+07:00,Pathum Thani,Pathum Thani,Clouds,few clouds,33.15,2025,5,1,11

In [18]:
path_single_partition = 's3a://weather/main/weather.parquet/year=2025/month=5/day=1/hour=11/8aeb52f0592d41f08e38c309edb03084-0.parquet'

df2=pd.read_parquet(    
    path=path_single_partition,
    storage_options=storage_options,
)
df2.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            4 non-null      datetime64[ns]
 1   minute               4 non-null      int64
 2   created_at           4 non-null      datetime64[ns, Asia/Bangkok]
 3   requested_province   4 non-null      object
 4   location             4 non-null      object
 5   weather_main         4 non-null      object
 6   weather_description  4 non-null      object
 7   main.temp            4 non-null      float64
 8   year                 4 non-null      category
 9   month                4 non-null      category
 10  day                  4 non-null      category
 11  hour                 4 non-null      category
dtypes: category(4), datetime64[ns, Asia/Bangkok](1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 788.0+ bytes

,timestamp,minute,created_at,requested_province,location,weather_main,weather_description,main.temp,year,month,day,hour
0,2025-05-01 11:31:10.350466,31,2025-05-01 11:49:10.333970+07:00,Pathum Thani,Pathum Thani,Clouds,few clouds,33.15,2025,5,1,11
1,2025-05-01 11:31:10.717529,31,2025-05-01 11:49:10.717493+07:00,Bangkok,Bangkok,Clouds,overcast clouds,33.94,2025,5,1,11
2,2025-05-01 11:31:11.057869,31,2025-05-01 11:49:11.057842+07:00,Chiang Mai,Chiang Mai,Clouds,few clouds,31.28,2025,5,1,11
3,2025-05-01 11:31:11.341738,31,2025-05-01 11:49:11.341696+07:00,Phuket,Kathu,Rain,moderate rain,25.92,2025,5,1,11

In [19]:
print(dt)

2025-05-01 11:31:40.647329+06:42

# Test Duck and Dask

In [34]:
# !pip install duckdb
import duckdb
import pandas as pd

# Connect to an in-memory DuckDB instance.
con = duckdb.connect(database=':memory:')

storage_options = {
    "key": ACCESS_KEY,
    "secret": SECRET_KEY,
    "client_kwargs": {
        "endpoint_url": lakefs_endpoint
    }
}

# Use DuckDB's read_parquet() function to read the dataset.
# Assume the dataset is stored in the directory "output_parquet_dataset" with hive partitions:
# output_parquet_dataset/year=2025/month=02/day=17/...
query = """
INSTALL httpfs;
LOAD httpfs;

SET s3_endpoint='localhost:8001';
SET s3_access_key_id='access_key'; 
SET s3_secret_access_key='secret_key'; 
SET s3_url_style='path';
SET s3_use_ssl=false;

SELECT *
FROM read_parquet('s3://weather/main/weather.parquet');
"""

df_duck = con.execute(query).df()

print("DuckDB Parquet Query Result:")
df_duck.info()
df_duck.head(20)

IOException: IO Error: Could not establish connection error for HTTP HEAD to 'http://localhost:8001/weather/main/weather.parquet' with status -597693936

In [38]:
!pip install dask

Requirement already satisfied: dask in /usr/local/lib/python3.11/site-packages (2025.4.1)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.11/site-packages (from dask) (8.1.7)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.11/site-packages (from dask) (3.0.0)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.11/site-packages (from dask) (2025.3.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/site-packages (from dask) (24.1)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.11/site-packages (from dask) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/site-packages (from dask) (6.0.1)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.11/site-packages (from dask) (1.0.0)
Requirement already satisfied: importlib_metadata>=4.13.0 in /usr/local/lib/python3.11/site-packages (from dask) (8.7.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/site-packages (from importlib_metadata>=4.13.0->dask) (3.21.0)
Requirement already satisfied: locket in /usr/local/lib/python3.11/site-packages (from partd>=1.4.0->dask) (1.0.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.1
[notice] To update, run: pip install --upgrade pip

In [39]:
import dask.dataframe as dd
df2 = dd.read_parquet(
    path=path_all_partition,
    storage_options=storage_options,
    dtype_backend='pyarrow'
)